import type { CurveConfig, ParamDef } from "./types";
import * as f from "./factories";

const P = (key: string, label: string, min: number, max: number, step: number): ParamDef => ({
  key, label, min, max, step,
});

export const curves: CurveConfig[] = [
  // ── Rose variants ───────────────────────────────────────
  { name: "Original Thinking", tag: "Custom Rose Trail", point: f.customRosePoint(7, 3, 7, 3.9), progress: 0.38, duration: 4.6, strokeWidth: 5.5, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.customRosePoint(a.R, a.A, a.k, a.sc), args: { R: 7, A: 3, k: 7, sc: 3.9 },
    params: [P("R", "Base Radius", 2, 12, 0.1), P("A", "Detail Amp", 0.5, 6, 0.1), P("k", "Petals", 2, 15, 1), P("sc", "Scale", 1, 6, 0.1)] },
  { name: "Thinking Five", tag: "Custom Rose Trail", point: f.customRosePoint(7, 3, 5, 3.9), progress: 0.38, duration: 4.6, strokeWidth: 5.5, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.customRosePoint(a.R, a.A, a.k, a.sc), args: { R: 7, A: 3, k: 5, sc: 3.9 },
    params: [P("R", "Base Radius", 2, 12, 0.1), P("A", "Detail Amp", 0.5, 6, 0.1), P("k", "Petals", 2, 15, 1)] },
  { name: "Thinking Nine", tag: "Custom Rose Trail", point: f.customRosePoint(7, 3, 9, 3.9), progress: 0.39, duration: 4.7, strokeWidth: 5.5, rotate: 30, breathe: 4.2,
    rebuild: (a) => f.customRosePoint(a.R, a.A, a.k, a.sc), args: { R: 7, A: 3, k: 9, sc: 3.9 },
    params: [P("R", "Base Radius", 2, 12, 0.1), P("A", "Detail Amp", 0.5, 6, 0.1), P("k", "Petals", 2, 15, 1)] },
  { name: "Rose Orbit", tag: "r = cos(k\u03b8)", point: f.roseOrbitPoint(7, 2.7, 7, 3.9), progress: 0.42, duration: 5.2, strokeWidth: 5.2, rotate: 28, breathe: 4.6,
    rebuild: (a) => f.roseOrbitPoint(a.R, a.A, a.k, a.sc), args: { R: 7, A: 2.7, k: 7, sc: 3.9 },
    params: [P("R", "Orbit Radius", 3, 12, 0.1), P("A", "Detail Amp", 0.5, 5, 0.1), P("k", "k", 2, 12, 1)] },
  { name: "Rose Curve", tag: "r = a cos(5\u03b8)", point: f.roseCurvePoint(9.2, 0.6, 0.72, 0.28, 5, 3.25), progress: 0.32, duration: 5.4, strokeWidth: 4.5, rotate: 28, breathe: 4.6,
    rebuild: (a) => f.roseCurvePoint(a.a, a.aB, 0.72, 0.28, a.k, a.sc), args: { a: 9.2, aB: 0.6, k: 5, sc: 3.25 },
    params: [P("a", "Amplitude", 5, 14, 0.1), P("k", "k", 2, 10, 1), P("sc", "Scale", 2, 5, 0.05)] },
  { name: "Rose Two", tag: "r = a cos(2\u03b8)", point: f.roseCurvePoint(9.2, 0.6, 0.72, 0.28, 2, 3.25), progress: 0.30, duration: 5.2, strokeWidth: 4.6, rotate: 28, breathe: 4.3,
    rebuild: (a) => f.roseCurvePoint(a.a, 0.6, 0.72, 0.28, a.k, a.sc), args: { a: 9.2, k: 2, sc: 3.25 },
    params: [P("a", "Amplitude", 5, 14, 0.1), P("k", "k", 2, 10, 1)] },
  { name: "Rose Three", tag: "r = a cos(3\u03b8)", point: f.roseCurvePoint(9.2, 0.6, 0.72, 0.28, 3, 3.25), progress: 0.31, duration: 5.3, strokeWidth: 4.6, rotate: 28, breathe: 4.4,
    rebuild: (a) => f.roseCurvePoint(a.a, 0.6, 0.72, 0.28, a.k, a.sc), args: { a: 9.2, k: 3, sc: 3.25 },
    params: [P("a", "Amplitude", 5, 14, 0.1), P("k", "k", 2, 10, 1)] },
  { name: "Rose Four", tag: "r = a cos(4\u03b8)", point: f.roseCurvePoint(9.2, 0.6, 0.72, 0.28, 4, 3.25), progress: 0.32, duration: 5.4, strokeWidth: 4.6, rotate: 28, breathe: 4.5,
    rebuild: (a) => f.roseCurvePoint(a.a, 0.6, 0.72, 0.28, a.k, a.sc), args: { a: 9.2, k: 4, sc: 3.25 },
    params: [P("a", "Amplitude", 5, 14, 0.1), P("k", "k", 2, 10, 1)] },

  // ── Lissajous / Lemniscate ──────────────────────────────
  { name: "Lissajous Drift", tag: "x=sin(at), y=sin(bt)", point: f.lissajousPoint(24, 6, 3, 4, 1.57, 0.92), progress: 0.34, duration: 6.0, strokeWidth: 4.7, rotate: 0, breathe: 5.4,
    rebuild: (a) => f.lissajousPoint(a.amp, 6, a.a, a.b, a.ph, a.yS), args: { amp: 24, a: 3, b: 4, ph: 1.57, yS: 0.92 },
    params: [P("a", "Freq X", 1, 8, 1), P("b", "Freq Y", 1, 8, 1), P("amp", "Amplitude", 10, 40, 0.5), P("ph", "Phase", 0, 6.28, 0.05), P("yS", "Y Scale", 0.4, 1.4, 0.01)] },
  { name: "Lemniscate Bloom", tag: "Bernoulli Lemniscate", point: f.lemniscatePoint(20, 7), progress: 0.40, duration: 5.6, strokeWidth: 4.8, rotate: 0, breathe: 5.0,
    rebuild: (a) => f.lemniscatePoint(a.a, a.bo), args: { a: 20, bo: 7 },
    params: [P("a", "Size", 8, 30, 0.5), P("bo", "Pulse", 0, 12, 0.1)] },

  // ── Spirograph variants ─────────────────────────────────
  { name: "Hypotrochoid Loop", tag: "Inner Spirograph", point: f.hypotrochoidPoint(8.2, 2.7, 0.45, 4.8, 1.2, 3.05), progress: 0.46, duration: 7.6, strokeWidth: 4.6, rotate: 0, breathe: 6.2,
    rebuild: (a) => f.hypotrochoidPoint(a.R, a.r, 0.45, a.d, 1.2, a.sc), args: { R: 8.2, r: 2.7, d: 4.8, sc: 3.05 },
    params: [P("R", "R", 3, 12, 0.1), P("r", "r", 0.5, 5, 0.1), P("d", "d", 1, 8, 0.1), P("sc", "Scale", 1.5, 4.5, 0.05)] },
  { name: "Three-Petal Spiral", tag: "R=3, r=1, d=3", point: f.petalSpiralPoint(3, 1, 3, 2.2, 0.45), progress: 0.34, duration: 4.6, strokeWidth: 4.4, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.petalSpiralPoint(a.R, a.r, a.d, 2.2, 0.45), args: { R: 3, r: 1, d: 3 },
    params: [P("R", "R", 2, 8, 1), P("r", "r", 0.5, 3, 0.1), P("d", "d", 1, 5, 0.1)] },
  { name: "Four-Petal Spiral", tag: "R=4, r=1, d=3", point: f.petalSpiralPoint(4, 1, 3, 2.2, 0.45), progress: 0.34, duration: 4.6, strokeWidth: 4.4, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.petalSpiralPoint(a.R, a.r, a.d, 2.2, 0.45), args: { R: 4, r: 1, d: 3 },
    params: [P("R", "R", 2, 8, 1), P("r", "r", 0.5, 3, 0.1), P("d", "d", 1, 5, 0.1)] },
  { name: "Five-Petal Spiral", tag: "R=5, r=1, d=3", point: f.petalSpiralPoint(5, 1, 3, 2.2, 0.45), progress: 0.34, duration: 4.6, strokeWidth: 4.4, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.petalSpiralPoint(a.R, a.r, a.d, 2.2, 0.45), args: { R: 5, r: 1, d: 3 },
    params: [P("R", "R", 2, 8, 1), P("r", "r", 0.5, 3, 0.1), P("d", "d", 1, 5, 0.1)] },
  { name: "Six-Petal Spiral", tag: "R=6, r=1, d=3", point: f.petalSpiralPoint(6, 1, 3, 2.2, 0.45), progress: 0.34, duration: 4.6, strokeWidth: 4.4, rotate: 28, breathe: 4.2,
    rebuild: (a) => f.petalSpiralPoint(a.R, a.r, a.d, 2.2, 0.45), args: { R: 6, r: 1, d: 3 },
    params: [P("R", "R", 2, 8, 1), P("r", "r", 0.5, 3, 0.1), P("d", "d", 1, 5, 0.1)] },

  // ── Special shapes ──────────────────────────────────────
  { name: "Butterfly Phase", tag: "Butterfly Curve", point: f.butterflyPoint(12, 4.6, 0.45, 2, 5), progress: 0.32, duration: 9.0, strokeWidth: 4.4, rotate: 0, breathe: 7.0, steps: 960,
    rebuild: (a) => f.butterflyPoint(a.turns, a.sc, 0.45, a.cw, a.pw), args: { turns: 12, sc: 4.6, cw: 2, pw: 5 },
    params: [P("turns", "Turns", 4, 18, 0.5), P("cw", "Cos Weight", 0.5, 4, 0.05), P("pw", "Power", 2, 8, 1), P("sc", "Scale", 2.5, 7, 0.05)] },
  { name: "Cardioid Glow", tag: "Cardioid", point: f.cardioidGlowPoint(8.4, 0.8, 2.15), progress: 0.36, duration: 6.2, strokeWidth: 4.9, rotate: 0, breathe: 5.2,
    rebuild: (a) => f.cardioidGlowPoint(a.a, a.pu, a.sc), args: { a: 8.4, pu: 0.8, sc: 2.15 },
    params: [P("a", "Size", 4, 14, 0.1), P("pu", "Pulse", 0, 2, 0.05), P("sc", "Scale", 1, 3.5, 0.05)] },
  { name: "Cardioid Heart", tag: "r = a(1+cos\u03b8)", point: f.cardioidHeartPoint(8.8, 0.8, 2.15), progress: 0.36, duration: 6.2, strokeWidth: 4.9, rotate: 0, breathe: 5.2,
    rebuild: (a) => f.cardioidHeartPoint(a.a, a.pu, a.sc), args: { a: 8.8, pu: 0.8, sc: 2.15 },
    params: [P("a", "Size", 4, 14, 0.1), P("pu", "Pulse", 0, 2, 0.05)] },
  { name: "Heart Wave", tag: "f(x) Heart Wave", point: f.heartWavePoint(6.4, 3.3, 0.9, 23.2, 24.5), progress: 0.18, duration: 8.4, strokeWidth: 3.9, rotate: 0, breathe: 5.6, open: true, alternate: true,
    rebuild: (a) => f.heartWavePoint(a.b, a.root, a.amp, 23.2, 24.5), args: { b: 6.4, root: 3.3, amp: 0.9 },
    params: [P("b", "Wave Freq", 2, 12, 0.1), P("root", "Root Span", 2.2, 4.2, 0.05), P("amp", "Wave Amp", 0.3, 1.6, 0.05)] },

  // ── Spirals ─────────────────────────────────────────────
  { name: "Spiral Search", tag: "Archimedean Spiral", point: f.spiralSearchPoint(4, 8, 8.5, 2.4, 1), progress: 0.28, duration: 7.8, strokeWidth: 4.3, rotate: 0, breathe: 6.8,
    rebuild: (a) => f.spiralSearchPoint(a.turns, a.base, a.rA, 2.4, 1), args: { turns: 4, base: 8, rA: 8.5 },
    params: [P("turns", "Turns", 2, 8, 0.1), P("base", "Base Radius", 2, 16, 0.1), P("rA", "Radius Amp", 2, 16, 0.1)] },
  { name: "Fourier Flow", tag: "Fourier Curve", point: f.fourierFlowPoint(17, 7.5, 3.2, 15, 8.2, 4.2, 1, 0.16), progress: 0.31, duration: 8.4, strokeWidth: 4.2, rotate: 0, breathe: 6.8,
    rebuild: (a) => f.fourierFlowPoint(a.x1, a.x3, a.x5, a.y1, a.y2, a.y4, 1, 0.16), args: { x1: 17, x3: 7.5, x5: 3.2, y1: 15, y2: 8.2, y4: 4.2 },
    params: [P("x1", "x cos1", 4, 24, 0.1), P("x3", "x cos3", 0, 14, 0.1), P("y1", "y sin1", 4, 24, 0.1), P("y2", "y sin2", 0, 14, 0.1)] },
  { name: "Fermat Spiral", tag: "r = a\u221a\u03b8", point: f.fermatSpiralPoint(4, 36), progress: 0.22, duration: 7.0, strokeWidth: 4.0, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.fermatSpiralPoint(a.turns, 36), args: { turns: 4 },
    params: [P("turns", "Turns", 1, 8, 0.5)] },
  { name: "Golden Spiral", tag: "r = ae^(b\u03b8)", point: f.logSpiralPoint(0.18, 3.5, 36), progress: 0.22, duration: 7.5, strokeWidth: 4.0, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.logSpiralPoint(a.b, a.turns, 36), args: { b: 0.18, turns: 3.5 },
    params: [P("b", "Growth Rate", 0.05, 0.4, 0.005), P("turns", "Turns", 1.5, 6, 0.5)] },
  { name: "Circle Involute", tag: "Involute of a Circle", point: f.involutePoint(3, 1.8), progress: 0.24, duration: 7.0, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.involutePoint(a.turns, 1.8), args: { turns: 3 },
    params: [P("turns", "Turns", 1, 6, 0.5)] },
  { name: "Lituus", tag: "r\u00b2\u03b8 = k", point: f.lituusPoint(12, 0.3, 7 * Math.PI, 4.5), progress: 0.25, duration: 7.0, strokeWidth: 4.0, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.lituusPoint(a.k, 0.3, 7 * Math.PI, 4.5), args: { k: 12 },
    params: [P("k", "k", 4, 30, 0.5)] },

  // ── Knots & Braids ──────────────────────────────────────
  { name: "Trefoil Knot", tag: "Topology Knot", point: f.trefoilKnotPoint(12), progress: 0.35, duration: 5.5, strokeWidth: 4.5, rotate: 0, breathe: 5.0 },
  { name: "Torus Knot", tag: "(3,2) Torus Knot", point: f.torusKnotPoint(11), progress: 0.30, duration: 6.0, strokeWidth: 4.3, rotate: 0, breathe: 5.2 },
  { name: "Epitrochoid", tag: "Outer Spirograph", point: f.epitrochoidPoint(5, 2, 3.5, 3), progress: 0.35, duration: 5.5, strokeWidth: 4.4, rotate: 24, breathe: 4.5,
    rebuild: (a) => f.epitrochoidPoint(a.R, a.r, a.d, a.sc), args: { R: 5, r: 2, d: 3.5, sc: 3 },
    params: [P("R", "R", 2, 10, 0.1), P("r", "r", 0.5, 5, 0.1), P("d", "d", 0.5, 6, 0.1), P("sc", "Scale", 1, 5, 0.05)] },

  // ── Organic / Nature ────────────────────────────────────
  { name: "Squircle", tag: "Superellipse n=4", point: f.superellipsePoint(4, 30, 30), progress: 0.30, duration: 4.5, strokeWidth: 5.0, rotate: 20, breathe: 4.0,
    rebuild: (a) => f.superellipsePoint(a.n, 30, 30), args: { n: 4 },
    params: [P("n", "Exponent", 0.5, 8, 0.1)] },
  { name: "Astroid", tag: "4-Cusped Hypocycloid", point: f.astroidPoint(28), progress: 0.32, duration: 4.8, strokeWidth: 4.8, rotate: 22, breathe: 4.2 },
  { name: "Deltoid", tag: "3-Cusped Hypocycloid", point: f.deltoidPoint(11), progress: 0.34, duration: 5.0, strokeWidth: 4.6, rotate: 24, breathe: 4.5 },
  { name: "Nephroid", tag: "Kidney Curve", point: f.nephroidPoint(7.5), progress: 0.34, duration: 5.2, strokeWidth: 4.7, rotate: 0, breathe: 5.0 },
  { name: "Cassini Oval", tag: "Product of Distances", point: f.cassiniOvalPoint(10, 12.5, 2.3), progress: 0.34, duration: 5.5, strokeWidth: 4.6, rotate: 0, breathe: 5.0,
    rebuild: (a) => f.cassiniOvalPoint(a.a, a.b, 2.3), args: { a: 10, b: 12.5 },
    params: [P("a", "Focus dist (a)", 4, 16, 0.1), P("b", "Product (b)", 6, 20, 0.1)] },

  // ── Exotic ──────────────────────────────────────────────
  { name: "Maurer Rose", tag: "n=2, d=1\u00b0", point: f.maurerRosePoint(2, 1, 28), progress: 0.08, duration: 12, strokeWidth: 3.2, rotate: 0, breathe: 6.5, steps: 360,
    rebuild: (a) => f.maurerRosePoint(a.n, a.d, 28), args: { n: 2, d: 1 },
    params: [P("n", "n", 2, 10, 1), P("d", "d (degrees)", 1, 180, 1)] },
  { name: "Harmonograph", tag: "Damped Pendulum", point: f.harmonographPoint(), progress: 0.15, duration: 10, strokeWidth: 3.8, rotate: 0, breathe: 6.0, open: true, alternate: true, steps: 960 },

  // ── Geometric ───────────────────────────────────────────
  { name: "Circle", tag: "r = const", point: f.circlePoint(30), progress: 0.30, duration: 3.5, strokeWidth: 5.0, rotate: 0, breathe: 4.0 },
  { name: "Rounded Pentagon", tag: "5-fold Symmetry", point: f.roundedPolygonPoint(5, 28, 0.18), progress: 0.30, duration: 4.5, strokeWidth: 5.0, rotate: 18, breathe: 4.0,
    rebuild: (a) => f.roundedPolygonPoint(a.sides, 28, a.amp), args: { sides: 5, amp: 0.18 },
    params: [P("sides", "Sides", 3, 12, 1), P("amp", "Shape", 0, 0.5, 0.01)] },
  { name: "Octagon", tag: "8-fold Symmetry", point: f.roundedPolygonPoint(8, 28, 0.08), progress: 0.30, duration: 4.0, strokeWidth: 5.0, rotate: 0, breathe: 4.0,
    rebuild: (a) => f.roundedPolygonPoint(a.sides, 28, a.amp), args: { sides: 8, amp: 0.08 },
    params: [P("sides", "Sides", 3, 12, 1), P("amp", "Shape", 0, 0.5, 0.01)] },
  { name: "Reuleaux Triangle", tag: "Constant Width", point: f.reuleauxTrianglePoint(22), progress: 0.32, duration: 4.8, strokeWidth: 5.0, rotate: 20, breathe: 4.2 },

  // ── Classical / Algebraic Curves ────────────────────────
  { name: "Witch of Agnesi", tag: "Agnesi Curve", point: f.witchOfAgnesiPoint(4, 6), progress: 0.2, duration: 7, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.witchOfAgnesiPoint(a.a, a.range), args: { a: 4, range: 6 },
    params: [P("a", "Size", 1, 8, 0.1), P("range", "Range", 2, 10, 0.5)] },
  { name: "Folium of Descartes", tag: "Leaf Curve", point: f.foliumPoint(3, 2), progress: 0.2, duration: 8, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.foliumPoint(a.a, a.scale), args: { a: 3, scale: 2 },
    params: [P("a", "Size", 1, 10, 0.1), P("scale", "Scale", 1, 5, 0.1)] },
  { name: "Cissoid", tag: "Cissoid of Diocles", point: f.cissoidPoint(8), progress: 0.25, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.cissoidPoint(a.a), args: { a: 8 },
    params: [P("a", "Size", 2, 15, 0.5)] },
  { name: "Conchoid", tag: "Conchoid of Nicomedes", point: f.conchoidPoint(3, 5, 1), progress: 0.25, duration: 7, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.conchoidPoint(a.a, a.b, 1), args: { a: 3, b: 5 },
    params: [P("a", "a", 1, 10, 0.1), P("b", "b", 1, 10, 0.1)] },

  // ── Additional Knots & Lissajous ────────────────────────
  { name: "Cinquefoil Knot", tag: "(2,5) Torus Knot", point: f.cinquefoilKnotPoint(11), progress: 0.3, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5 },
  { name: "Figure-Eight Knot", tag: "(2,3) Torus Knot", point: f.figureEightKnotPoint(11), progress: 0.3, duration: 5.5, strokeWidth: 4.3, rotate: 0, breathe: 5.2 },
  { name: "Lissajous 3:5", tag: "Lissajous Knot", point: f.lissajousKnotPoint(28), progress: 0.3, duration: 6, strokeWidth: 4.5, rotate: 0, breathe: 5.4 },

  // ── Roses & Superformula ────────────────────────────────
  { name: "Rhodonea 7/3", tag: "Fractional Rose", point: f.fractionalRosePoint(2.333, 28), progress: 0.2, duration: 8, strokeWidth: 4, rotate: 0, breathe: 5.5, steps: 720,
    rebuild: (a) => f.fractionalRosePoint(a.k, 28), args: { k: 2.333 },
    params: [P("k", "k", 0.5, 5, 0.1)] },
  { name: "Starfish", tag: "Superformula", point: f.starfishPoint(5, 0.3, 28), progress: 0.3, duration: 5, strokeWidth: 4.5, rotate: 18, breathe: 4.5,
    rebuild: (a) => f.starfishPoint(a.m, a.n1, 28), args: { m: 5, n1: 0.3 },
    params: [P("m", "Arms", 3, 10, 1), P("n1", "Shape", 0.1, 5, 0.1)] },
  { name: "Superformula", tag: "Gielis Curve", point: f.superformulaPoint(6, 1, 1, 1, 28), progress: 0.3, duration: 5, strokeWidth: 4.5, rotate: 0, breathe: 4.5,
    rebuild: (a) => f.superformulaPoint(a.m, a.n1, a.n2, a.n3, 28), args: { m: 6, n1: 1, n2: 1, n3: 1 },
    params: [P("m", "Symmetry", 1, 12, 1), P("n1", "n1", 0.1, 5, 0.1), P("n2", "n2", 0.1, 5, 0.1), P("n3", "n3", 0.1, 5, 0.1)] },

  // ── Epicycloid & Spirals ────────────────────────────────
  { name: "Ranunculoid", tag: "Buttercup Epicycloid", point: f.ranunculoidPoint(5, 1, 3), progress: 0.3, duration: 5, strokeWidth: 4.4, rotate: 20, breathe: 4.5,
    rebuild: (a) => f.ranunculoidPoint(a.R, a.r, 3), args: { R: 5, r: 1 },
    params: [P("R", "R", 2, 10, 1), P("r", "r", 0.5, 3, 0.1)] },
  { name: "Cornu Spiral", tag: "Euler Spiral", point: f.cornuSpiralPoint(5, 12), progress: 0.2, duration: 8, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.cornuSpiralPoint(a.maxT, 12), args: { maxT: 5 },
    params: [P("maxT", "Range", 2, 8, 0.5)] },
  { name: "Fibonacci Spiral", tag: "Golden Ratio Spiral", point: f.fibonacciSpiralPoint(2, 0.08), progress: 0.2, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.fibonacciSpiralPoint(a.turns, 0.08), args: { turns: 2 },
    params: [P("turns", "Turns", 1, 4, 0.5)] },
  { name: "Hyperbolic Spiral", tag: "r = a/\u03b8", point: f.hyperbolicSpiralPoint(10, 0.3, 7 * Math.PI, 4.5), progress: 0.25, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.hyperbolicSpiralPoint(a.a, 0.3, 7 * Math.PI, 4.5), args: { a: 10 },
    params: [P("a", "a", 2, 20, 0.5)] },

  // ── Additional Shapes ───────────────────────────────────
  { name: "Gerono Lemniscate", tag: "Figure-Eight", point: f.geronoLemniscatePoint(28), progress: 0.35, duration: 5, strokeWidth: 4.8, rotate: 0, breathe: 5 },
  { name: "Scarabaeus", tag: "Beetle Curve", point: f.scarabaeusPoint(1.5, 2, 12), progress: 0.3, duration: 5.5, strokeWidth: 4.5, rotate: 0, breathe: 5,
    rebuild: (a) => f.scarabaeusPoint(a.a, a.b, 12), args: { a: 1.5, b: 2 },
    params: [P("a", "a", 0.5, 5, 0.1), P("b", "b", 0.5, 5, 0.1)] },

  // ── Mathematical Curves ────────────────────────────────
  { name: "Bicorn", tag: "Cocked Hat", point: f.bicornPoint(15), progress: 0.3, duration: 5, strokeWidth: 4.5, rotate: 0, breathe: 5,
    rebuild: (a) => f.bicornPoint(a.a), args: { a: 15 },
    params: [P("a", "Size", 5, 30, 0.5)] },
  { name: "Catenary", tag: "Hanging Chain", point: f.catenaryPoint(5, 3), progress: 0.25, duration: 6, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.catenaryPoint(a.a, a.range), args: { a: 5, range: 3 },
    params: [P("a", "Size", 2, 15, 0.5), P("range", "Range", 1, 5, 0.5)] },
  { name: "Cayley's Sextic", tag: "Sinusoidal Spiral", point: f.cayleySexticPoint(2, 1), progress: 0.3, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5, steps: 720,
    rebuild: (a) => f.cayleySexticPoint(a.a, 1), args: { a: 2 },
    params: [P("a", "a", 0.5, 5, 0.1)] },
  { name: "Cochleoid", tag: "Snail Spiral", point: f.cochleoidPoint(30, 6 * Math.PI), progress: 0.2, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.cochleoidPoint(a.a, 6 * Math.PI), args: { a: 30 },
    params: [P("a", "Size", 10, 60, 1)] },
  { name: "Conchoid de Sluze", tag: "Looped Conchoid", point: f.conchoidDeSluzePoint(-0.5, 10), progress: 0.25, duration: 7, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.conchoidDeSluzePoint(a.a, 10), args: { a: -0.5 },
    params: [P("a", "a", -2, 2, 0.1)] },
  { name: "Devil's Curve", tag: "Devil on Sticks", point: f.devilsCurvePoint(1, 0.8, 10), progress: 0.3, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5,
    rebuild: (a) => f.devilsCurvePoint(a.a, a.b, 10), args: { a: 1, b: 0.8 },
    params: [P("a", "a", 0.5, 5, 0.1), P("b", "b", 0.5, 5, 0.1)] },
  { name: "Double Folium", tag: "Two-Lobed Leaf", point: f.doubleFoliumPoint(1, 10), progress: 0.3, duration: 5.5, strokeWidth: 4.4, rotate: 0, breathe: 5,
    rebuild: (a) => f.doubleFoliumPoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Trifolium", tag: "Three-Lobed Clover", point: f.trifoliumPoint(1, 10), progress: 0.3, duration: 5, strokeWidth: 4.5, rotate: 0, breathe: 5,
    rebuild: (a) => f.trifoliumPoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Freeth's Nephroid", tag: "Modified Nephroid", point: f.freethNephroidPoint(1, 10), progress: 0.25, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5, steps: 720,
    rebuild: (a) => f.freethNephroidPoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Kampyle", tag: "Kampyle of Eudoxus", point: f.kampylePoint(1, 10), progress: 0.25, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.kampylePoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Kappa Curve", tag: "Gutschoven's Curve", point: f.kappaCurvePoint(1, 10), progress: 0.25, duration: 6, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.kappaCurvePoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Pear Quartic", tag: "Pear-Shaped", point: f.pearShapedPoint(3, 3, 3), progress: 0.3, duration: 5.5, strokeWidth: 4.4, rotate: 0, breathe: 5,
    rebuild: (a) => f.pearShapedPoint(a.a, a.b, 3), args: { a: 3, b: 3 },
    params: [P("a", "a", 1, 10, 0.1), P("b", "b", 1, 10, 0.1)] },
  { name: "Plateau Curve", tag: "Nested Loops", point: f.plateauCurvePoint(3, 1, 1, 10), progress: 0.25, duration: 7, strokeWidth: 4, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.plateauCurvePoint(a.m, a.n, 1, 10), args: { m: 3, n: 1 },
    params: [P("m", "m", 1, 8, 1), P("n", "n", 1, 8, 1)] },
  { name: "Right Strophoid", tag: "Belt with Twist", point: f.rightStrophoidPoint(1, 10), progress: 0.25, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.rightStrophoidPoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Serpentine", tag: "S-Curve", point: f.serpentinePoint(3, 4, 6), progress: 0.2, duration: 7, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.serpentinePoint(a.a, a.b, 6), args: { a: 3, b: 4 },
    params: [P("a", "a", 1, 8, 0.1), P("b", "b", 1, 10, 0.1)] },
  { name: "Sinusoidal Spiral", tag: "r^p = a^p cos(p\u03b8)", point: f.sinusoidalSpiralPoint(1.5, 1, 10), progress: 0.3, duration: 5.5, strokeWidth: 4.4, rotate: 0, breathe: 5,
    rebuild: (a) => f.sinusoidalSpiralPoint(a.pp, 1, 10), args: { pp: 1.5 },
    params: [P("pp", "p", 0.3, 3, 0.1)] },
  { name: "Spiric Section", tag: "Torus Cross-Section", point: f.spiricSectionPoint(2, 1, 10), progress: 0.3, duration: 5.5, strokeWidth: 4.4, rotate: 0, breathe: 5,
    rebuild: (a) => f.spiricSectionPoint(a.a, a.b, 10), args: { a: 2, b: 1 },
    params: [P("a", "a", 0.5, 5, 0.1), P("b", "b", 0.5, 5, 0.1)] },
  { name: "Talbot's Curve", tag: "Football Curve", point: f.talbotCurvePoint(1, 1.5, 0.8, 10), progress: 0.3, duration: 5.5, strokeWidth: 4.3, rotate: 0, breathe: 5,
    rebuild: (a) => f.talbotCurvePoint(a.a, a.b, a.f, 10), args: { a: 1, b: 1.5, f: 0.8 },
    params: [P("a", "a", 0.5, 3, 0.1), P("b", "b", 0.5, 3, 0.1), P("f", "f", 0.5, 2, 0.05)] },
  { name: "Tractrix", tag: "Drag Curve", point: f.tractrixPoint(5, 4, 3), progress: 0.25, duration: 7, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.tractrixPoint(a.a, 4, 3), args: { a: 5 },
    params: [P("a", "Size", 1, 10, 0.1)] },
  { name: "Tschirnhaus Cubic", tag: "Cubic Loop", point: f.tschirnhausCubicPoint(1, 3), progress: 0.25, duration: 6, strokeWidth: 4.3, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.tschirnhausCubicPoint(a.a, 3), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Trisectrix", tag: "Trisectrix of Maclaurin", point: f.trisectrixPoint(1, 10), progress: 0.25, duration: 6, strokeWidth: 4.2, rotate: 0, breathe: 5.5, open: true, alternate: true,
    rebuild: (a) => f.trisectrixPoint(a.a, 10), args: { a: 1 },
    params: [P("a", "Size", 0.5, 5, 0.1)] },
  { name: "Teardrop", tag: "Pearls of Sluze", point: f.teardropPoint(1, 1, 10), progress: 0.3, duration: 5.5, strokeWidth: 4.4, rotate: 0, breathe: 5,
    rebuild: (a) => f.teardropPoint(1, a.n, 10), args: { n: 1 },
    params: [P("n", "Exponent", 0.5, 5, 0.1)] },

  // ── Random ──────────────────────────────────────────────
  { name: "Random", tag: "Randomized Fourier", point: f.randomCurvePoint(f.generateRandomParams(42)), progress: 0.3, duration: 6, strokeWidth: 4.5, rotate: 0, breathe: 5 },
];
